/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RatingDto } from './RatingDto';
import {
    RatingDtoFromJSON,
    RatingDtoFromJSONTyped,
    RatingDtoToJSON,
} from './RatingDto';

/**
 * 
 * @export
 * @interface ExtendedRatingDto
 */
export interface ExtendedRatingDto {
    /**
     * 
     * @type {Date}
     * @memberof ExtendedRatingDto
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof ExtendedRatingDto
     */
    participantName?: string;
    /**
     * 
     * @type {RatingDto}
     * @memberof ExtendedRatingDto
     */
    rating?: RatingDto;
}

/**
 * Check if a given object implements the ExtendedRatingDto interface.
 */
export function instanceOfExtendedRatingDto(value: object): boolean {
    return true;
}

export function ExtendedRatingDtoFromJSON(json: any): ExtendedRatingDto {
    return ExtendedRatingDtoFromJSONTyped(json, false);
}

export function ExtendedRatingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtendedRatingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'participantName': json['participantName'] == null ? undefined : json['participantName'],
        'rating': json['rating'] == null ? undefined : RatingDtoFromJSON(json['rating']),
    };
}

export function ExtendedRatingDtoToJSON(value?: ExtendedRatingDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'participantName': value['participantName'],
        'rating': RatingDtoToJSON(value['rating']),
    };
}

