/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAuthZeroUserDto
 */
export interface UpdateAuthZeroUserDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateAuthZeroUserDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAuthZeroUserDto
     */
    givenName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAuthZeroUserDto
     */
    familyName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAuthZeroUserDto
     */
    role?: string;
}

/**
 * Check if a given object implements the UpdateAuthZeroUserDto interface.
 */
export function instanceOfUpdateAuthZeroUserDto(value: object): boolean {
    return true;
}

export function UpdateAuthZeroUserDtoFromJSON(json: any): UpdateAuthZeroUserDto {
    return UpdateAuthZeroUserDtoFromJSONTyped(json, false);
}

export function UpdateAuthZeroUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAuthZeroUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'givenName': json['given_name'] == null ? undefined : json['given_name'],
        'familyName': json['family_name'] == null ? undefined : json['family_name'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function UpdateAuthZeroUserDtoToJSON(value?: UpdateAuthZeroUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'given_name': value['givenName'],
        'family_name': value['familyName'],
        'role': value['role'],
    };
}

