apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-js-app-deployment
  labels:
    app: next-js-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-js-app
  template:
    metadata:
      labels:
        app: next-js-app
    spec:
      containers:
      - name: next-js-app
        image: <your-docker-image>:<tag>
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: next-js-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: next-js-app
