# Backend Build Stage
FROM gradle:8.6.0-jdk21 AS builder
WORKDIR /app
COPY ./backend/build.gradle .
COPY ./backend/settings.gradle .
COPY ./backend/src src
RUN gradle build --no-daemon --exclude-task test

# Testing Image Preparation
FROM gradle:8.6.0-jdk21
WORKDIR /app
COPY --from=builder /app/build /app/build
COPY --from=builder /app/src /app/src    
CMD ["gradle", "test"]                   
