# Backend Build Stage
FROM gradle:8.6.0-jdk21 AS builder
WORKDIR /app

# Copy the entire backend directory
COPY ./backend .

# Run the build process
RUN gradle assemble --no-daemon

# Set the entry point to start the server
CMD ["gradle", "bootRun"]
