coverage:
  status:
    project:
      default:
        target: 40%
        threshold: 5%
ignore:
  - "backend/src/main/java/ch/zhaw/pm4/compass/backend/model/dto/**/*"
  - "backend/src/main/java/ch/zhaw/pm4/compass/backend/exception/**/*"
  - "node_modules/**/*"
  - "public/**/*"
  - "migrations/**/*"
  - ".next/**/*"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/*.config.mjs"
  - "**/*.config.yml"
  - "test-results/**/*"
  - "tests/**/*"
  - "src/openapi/**/*"
  - "src/constants/**/*"
