#coverage:
#  status:
#    project:
#      default:
#        target: 70%
#        threshold: 5%
ignore:
  - "compass/backend/src/test/**/*"
  - "compass/backend/src/main/resources/**/*"
  - "compass/backend/src/main/java/ch/zhaw/pm4/compass/backend/model/dto/**/*"
  - "compass/backend/src/main/java/ch/zhaw/pm4/compass/backend/repository/**/*"
  - "compass/backend/src/main/java/ch/zhaw/pm4/compass/backend/exception/**/*""
  - "compass/frontend/node_modules/**/*"
  - "compass/frontend/public/**/*"
  - "compass/frontend/migrations/**/*"
  - "compass/frontend/.next/**/*"
  - "**/*.config.js"
  - "**/*.config.ts"
  - "**/*.config.mjs"
  - "**/*.config.yml"
  - "compass/frontend/test-results/**/*"
  - "compass/frontend/tests/**/*"
  - "compass/frontend/src/openapi/**/*"
  - "compass/frontend/src/constants/**/*"