version: "3.8"
services:
  app:
    build:
      context: ./
      target: builder
    volumes:
      - .:/app
    command: bash -c "npm run dev"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development