coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
ignore:
  - "src/test/**/*"
  - "src/main/resources/**/*"
  - "src/main/java/model/dto/**/*"
  - "src/main/java/repository/**/*"