/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Timestamp } from './timestamp';

export class GetDaySheetDto {
    'id'?: number;
    'date'?: Date;
    'dayReport'?: string;
    'confirmed'?: boolean;
    'timestamps'?: Array<Timestamp>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date"
        },
        {
            "name": "dayReport",
            "baseName": "day_report",
            "type": "string"
        },
        {
            "name": "confirmed",
            "baseName": "confirmed",
            "type": "boolean"
        },
        {
            "name": "timestamps",
            "baseName": "timestamps",
            "type": "Array<Timestamp>"
        }    ];

    static getAttributeTypeMap() {
        return GetDaySheetDto.attributeTypeMap;
    }
}

