name: "Run Backend Tests with PostgreSQL in Docker"
description: "Builds a Docker image and runs Gradle tests within the container, then uploads test coverage in a Java project"
inputs:
  working-directory:
    description: "The working directory where your backend project is located"
    required: true
    default: "./backend"
  codecov-token:
    description: "Codecov token for uploading coverage"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker Image
      shell: bash
      run: docker build -t backend-tests -f ./docker/test/Dockerfile.backend .

    - name: Start Backend Container
      shell: bash
      run: |
        docker run -d \
          -e DOCKER_ON='false' \
          -e PORT='8080' \
          -e DB_HOST='//host.docker.internal:5432/compass' \
          -e DB_USERNAME='postgres' \
          -e DB_PASSWORD='test_password' \
          -e DDL_AUTO='create' \
          -e AUTH0_ISSUER_BASE_URL='https://test.local' \
          -e AUTH0_AUDIENCE='test' \
          -e AUTH0_CLIENT_ID='' \
          -e AUTH0_CLIENT_SECRET='' \
          -e AUTH0_MGMT_AUDIENCE='https://test.local' \
          -e APP_URL='test.local' \
          --add-host host.docker.internal:host-gateway \
          -v $(pwd)/backend/build:/app/build \
          --name test-container \
          backend-tests

    - name: Wait for Backend to be Ready
      shell: bash
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:8080 > /dev/null; then
            echo 'Backend is ready!'
            exit 0
          fi
          echo 'Waiting for backend to be ready...'
          docker ps -a
          docker logs test-container || true
          sleep 5
        done
        echo 'Backend did not become ready in time'
        exit 1

    - name: Run Gradle Tests in Docker Container
      shell: bash
      run: docker exec test-container gradle test -info

    - name: Debug Copied Classes
      shell: bash
      run: ls -la ./backend/build

    - name: Upload Backend Test Results
      uses: actions/upload-artifact@v2
      with:
        name: backend-test-results
        path: ./backend/build

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov-token }}
        directory: ./backend/build/reports
        flags: backend
        fail_ci_if_error: true
        verbose: true
