name: "Run Backend Tests"
description: "Installs dependencies, runs Gradle tests, and uploads test coverage in a Java project"
inputs:
  working-directory:
    description: "The working directory where your backend project is located"
    required: true
    default: "./backend"
  codecov-token:
    description: "Codecov token for uploading coverage"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: "21"
        distribution: "temurin"

    - name: Grant execute permissions for Gradlew
      run: chmod +x ${{ inputs.working-directory }}/gradlew
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Run Gradle Tests
      run: ./gradlew test --info
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov-token }}
        directory: ${{ inputs.working-directory }}/build/reports
        flags: backend
        fail_ci_if_error: true
        verbose: true
