name: "Run Backend Tests"
description: "Installs dependencies, runs Gradle tests, and uploads test coverage in a Java project"
inputs:
  working-directory:
    description: "The working directory where your backend project is located"
    required: true
    default: "./backend"
  codecov-token:
    description: "Codecov token for uploading coverage"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"
    - name: Install dependencies, run tests, and collect coverage
      shell: bash
      run: cd ${{ inputs.working-directory }} && gradle build
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov-token }}
        directory: ${{ inputs.working-directory }}/build/reports
        flags: backend
        fail_ci_if_error: true
        verbose: true
