name: "Run Backend Tests with PostgreSQL in Docker"
description: "Builds a Docker image and runs Gradle tests within the container, then uploads test coverage in a Java project"
inputs:
  working-directory:
    description: "The working directory where your backend project is located"
    required: true
    default: "./backend"
  codecov-token:
    description: "Codecov token for uploading coverage"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Print working directory
      shell: bash
      run: pwd && ls -la

    - name: Build Docker Image
      shell: bash
      run: docker build -t backend-tests -f Dockerfile ./docker/test/Dockerfile.backend

    - name: Run Tests in Docker Container
      shell: bash
      run: docker run --name test-container backend-tests

    - name: Copy Coverage Reports from Docker Container
      shell: bash
      run: docker cp test-container:/app/build/reports ./reports

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ inputs.codecov-token }}
        directory: ./reports
        flags: backend
        fail_ci_if_error: true
        verbose: true
