# Use the official PHP image with Apache
FROM php:8.1-apache

# Copy the contents of the landing page to the web root
COPY ./landing /var/www/html/

# Enable Apache mod_rewrite for .htaccess
RUN a2enmod rewrite

# Set permissions
RUN chown -R www-data:www-data /var/www/html

# Copy .htaccess file
COPY ./landing/.htaccess /var/www/html/.htaccess

# Expose port 80
EXPOSE 80
