version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_compass
    environment:
      POSTGRES_DB: compass
      POSTGRES_PASSWORD: password
      POSTGRES_USER: dbadmin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: compass_backend
    container_name: compass_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/compass
      SPRING_DATASOURCE_USERNAME: dbadmin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - '8080:8080'

  frontend:
    image: compass_frontend
    container_name: compass_frontend
    depends_on:
      - backend
    ports:
      - '3000:3000'

volumes:
  postgres_data:
