/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Timestamp } from './Timestamp';
import {
    TimestampFromJSON,
    TimestampFromJSONTyped,
    TimestampToJSON,
} from './Timestamp';

/**
 * 
 * @export
 * @interface GetDaySheetDto
 */
export interface GetDaySheetDto {
    /**
     * 
     * @type {number}
     * @memberof GetDaySheetDto
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof GetDaySheetDto
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof GetDaySheetDto
     */
    dayReport?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetDaySheetDto
     */
    confirmed?: boolean;
    /**
     * 
     * @type {Array<Timestamp>}
     * @memberof GetDaySheetDto
     */
    timestamps?: Array<Timestamp>;
}

/**
 * Check if a given object implements the GetDaySheetDto interface.
 */
export function instanceOfGetDaySheetDto(value: object): boolean {
    return true;
}

export function GetDaySheetDtoFromJSON(json: any): GetDaySheetDto {
    return GetDaySheetDtoFromJSONTyped(json, false);
}

export function GetDaySheetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetDaySheetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'dayReport': json['day_report'] == null ? undefined : json['day_report'],
        'confirmed': json['confirmed'] == null ? undefined : json['confirmed'],
        'timestamps': json['timestamps'] == null ? undefined : ((json['timestamps'] as Array<any>).map(TimestampFromJSON)),
    };
}

export function GetDaySheetDtoToJSON(value?: GetDaySheetDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'day_report': value['dayReport'],
        'confirmed': value['confirmed'],
        'timestamps': value['timestamps'] == null ? undefined : ((value['timestamps'] as Array<any>).map(TimestampToJSON)),
    };
}

