/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDaySheetDto
 */
export interface UpdateDaySheetDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateDaySheetDto
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof UpdateDaySheetDto
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateDaySheetDto
     */
    dayReport?: string;
}

/**
 * Check if a given object implements the UpdateDaySheetDto interface.
 */
export function instanceOfUpdateDaySheetDto(value: object): boolean {
    return true;
}

export function UpdateDaySheetDtoFromJSON(json: any): UpdateDaySheetDto {
    return UpdateDaySheetDtoFromJSONTyped(json, false);
}

export function UpdateDaySheetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDaySheetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'dayReport': json['day_report'] == null ? undefined : json['day_report'],
    };
}

export function UpdateDaySheetDtoToJSON(value?: UpdateDaySheetDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'date': value['date'] == null ? undefined : ((value['date']).toISOString()),
        'day_report': value['dayReport'],
    };
}

