/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTimestampDto
 */
export interface UpdateTimestampDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateTimestampDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateTimestampDto
     */
    daySheetId?: number;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTimestampDto
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTimestampDto
     */
    endTime?: Date;
}

/**
 * Check if a given object implements the UpdateTimestampDto interface.
 */
export function instanceOfUpdateTimestampDto(value: object): boolean {
    return true;
}

export function UpdateTimestampDtoFromJSON(json: any): UpdateTimestampDto {
    return UpdateTimestampDtoFromJSONTyped(json, false);
}

export function UpdateTimestampDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTimestampDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'daySheetId': json['day_sheet_id'] == null ? undefined : json['day_sheet_id'],
        'startTime': json['start_time'] == null ? undefined : (new Date(json['start_time'])),
        'endTime': json['end_time'] == null ? undefined : (new Date(json['end_time'])),
    };
}

export function UpdateTimestampDtoToJSON(value?: UpdateTimestampDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'day_sheet_id': value['daySheetId'],
        'start_time': value['startTime'] == null ? undefined : ((value['startTime']).toISOString()),
        'end_time': value['endTime'] == null ? undefined : ((value['endTime']).toISOString()),
    };
}

