name: "Run E2E Tests"
description: "Installs dependencies and runs end-to-end tests in a Node.js project"
inputs:
  working-directory:
    description: "The working directory where your frontend project is located"
    required: true
    default: "./frontend"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14"

    - name: Install Dependencies
      run: |
        cd ${{ inputs.working-directory }}
        npm install
      shell: bash

    - name: Run E2E Tests
      run: |
        cd ${{ inputs.working-directory }}
        npm run test:e2e
      shell: bash

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: e2e-test-results
        path: ${{ inputs.working-directory }}/e2e-results/**/*
