apiVersion: apps/v1
kind: Deployment
metadata:
  name: compass-deployment
  namespace: compass-prod
  labels:
    app: compass-app
  annotations:
    forceReDeploy: "INITIAL_VALUE"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compass-app
  template:
    metadata:
      labels:
        app: compass-app
    spec:
      containers:
      - name: my-container
        image: pm4compass/compass:latest #image 
        ports:
        - containerPort: 3000
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: DB_HOST
        - name: DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: DDL_AUTO
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DB_PASSWORD
      imagePullSecrets:
      - name: docker-credentials