/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DaySheetDto,
  UpdateDaySheetDayNotesDto,
} from '../models/index';
import {
    DaySheetDtoFromJSON,
    DaySheetDtoToJSON,
    UpdateDaySheetDayNotesDtoFromJSON,
    UpdateDaySheetDayNotesDtoToJSON,
} from '../models/index';

export interface CreateDaySheetRequest {
    daySheetDto: DaySheetDto;
}

export interface GetAllDaySheetByParticipantRequest {
    userId: string;
}

export interface GetDaySheetByDateRequest {
    date: string;
}

export interface GetDaySheetByIdRequest {
    id: number;
}

export interface UpdateConfirmedRequest {
    id: number;
}

export interface UpdateDayNotesRequest {
    updateDaySheetDayNotesDto: UpdateDaySheetDayNotesDto;
}

/**
 * 
 */
export class DaySheetControllerApi extends runtime.BaseAPI {

    /**
     */
    async createDaySheetRaw(requestParameters: CreateDaySheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['daySheetDto'] == null) {
            throw new runtime.RequiredError(
                'daySheetDto',
                'Required parameter "daySheetDto" was null or undefined when calling createDaySheet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/daysheet`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DaySheetDtoToJSON(requestParameters['daySheetDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async createDaySheet(requestParameters: CreateDaySheetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.createDaySheetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getAllDaySheetByParticipantRaw(requestParameters: GetAllDaySheetByParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DaySheetDto>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getAllDaySheetByParticipant().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/getAllByParticipant/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DaySheetDtoFromJSON));
    }

    /**
     */
    async getAllDaySheetByParticipant(requestParameters: GetAllDaySheetByParticipantRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DaySheetDto>> {
        const response = await this.getAllDaySheetByParticipantRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getDaySheetByDateRaw(requestParameters: GetDaySheetByDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling getDaySheetByDate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/getByDate/{date}`.replace(`{${"date"}}`, encodeURIComponent(String(requestParameters['date']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async getDaySheetByDate(requestParameters: GetDaySheetByDateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.getDaySheetByDateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getDaySheetByIdRaw(requestParameters: GetDaySheetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDaySheetById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/getById/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async getDaySheetById(requestParameters: GetDaySheetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.getDaySheetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateConfirmedRaw(requestParameters: UpdateConfirmedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateConfirmed().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/daysheet/confirm/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async updateConfirmed(requestParameters: UpdateConfirmedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.updateConfirmedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateDayNotesRaw(requestParameters: UpdateDayNotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DaySheetDto>> {
        if (requestParameters['updateDaySheetDayNotesDto'] == null) {
            throw new runtime.RequiredError(
                'updateDaySheetDayNotesDto',
                'Required parameter "updateDaySheetDayNotesDto" was null or undefined when calling updateDayNotes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/daysheet/updateDayNotes`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDaySheetDayNotesDtoToJSON(requestParameters['updateDaySheetDayNotesDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DaySheetDtoFromJSON(jsonValue));
    }

    /**
     */
    async updateDayNotes(requestParameters: UpdateDayNotesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DaySheetDto> {
        const response = await this.updateDayNotesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
