/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RatingDto,
} from '../models/index';
import {
    RatingDtoFromJSON,
    RatingDtoToJSON,
} from '../models/index';

export interface CreateRatingRequest {
    ratingDto: RatingDto;
}

/**
 * 
 */
export class RatingControllerApi extends runtime.BaseAPI {

    /**
     */
    async createRatingRaw(requestParameters: CreateRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RatingDto>> {
        if (requestParameters['ratingDto'] == null) {
            throw new runtime.RequiredError(
                'ratingDto',
                'Required parameter "ratingDto" was null or undefined when calling createRating().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/rating`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RatingDtoToJSON(requestParameters['ratingDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RatingDtoFromJSON(jsonValue));
    }

    /**
     */
    async createRating(requestParameters: CreateRatingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RatingDto> {
        const response = await this.createRatingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
