name: Deploy to Production

on:
  push:
    tags:
      - "release/*"
  workflow_dispatch: # enables manual trigger

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run E2E Tests
        uses: ./.github/actions/e2e-test-action
        with:
          working-directory: "./frontend"

  build:
    needs: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker Image
        uses: ./.github/workflows/build-push-docker
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          image_tag: pm4compass/compass:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set Up K8s and Redeploy
        uses: ./.github/actions/setup-redeploy-k8s
        with:
          kubeconfig_data: ${{ secrets.KUBE_CONFIG_DATA }}
          image_tag: pm4compass/compass:latest
          namespace: compass-prod
