name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch: # enables manual trigger

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run E2E Tests
        uses: ./.github/actions/e2e-test-action
        with:
          working-directory: "./frontend"

  build-backend:
    needs: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Backend Docker Image
        uses: ./.github/actions/build-push-docker-backend
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          image_tag: pm4compass/compass-backend:latest

  build-frontend:
    needs: e2e-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Frontend Docker Image
        uses: ./.github/actions/build-push-docker-frontend
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          image_tag: pm4compass/compass-frontend:latest

  deploy-backend:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Set Up K8s and Redeploy Backend
        uses: ./.github/actions/setup-redeploy-k8s-backend
        with:
          kubeconfig_data: ${{ secrets.KUBE_CONFIG_DATA }}
          backend_image_tag: pm4compass/compass-backend:latest
          namespace: compass-prod

  deploy-frontend:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Set Up K8s and Redeploy Frontend
        uses: ./.github/actions/setup-redeploy-k8s-frontend
        with:
          kubeconfig_data: ${{ secrets.KUBE_CONFIG_DATA }}
          frontend_image_tag: pm4compass/compass-frontend:latest
          namespace: compass-prod
