name: Build, Push and Deploy - Staging

on:
  push:
    branches:
      - main
  workflow_dispatch: # enables manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pm4compass/compass:${{ github.sha }}

      - name: Set up K8s context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy to Kubernetes and Trigger Redeployment
        run: |
          kubectl set image deployment/compass-deployment my-container=pm4compass/compass:${{ github.sha }} -n compass-stage
          kubectl patch deployment compass-deployment -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"forceReDeploy\":\"$(date +%s)\"}}}}}" -n compass-stage
