name: Front and Backend Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: # enables manual trigger

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run E2E Tests and Upload Coverage
        uses: ./.github/actions/run-e2e-tests
        with:
          working-directory: "./frontend"
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
